name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run flake8
        run: make flake8
      - name: Run mypy
        run: make mypy
      - name: Run isort check
        run: make isort-check
